# Site
repository: myalfred03/myalfred03.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Yeser Alfredo Morales
title: Electronic Engineer
email: myalfredo03@ieee.org
# email_title: Email (Email title override)
#phone: Your phone number (optional)
website: myalfredo03.wordpress.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: myalfred03
github_username:  myalfred03
linkedin_username: myalfredo03

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/me2.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi there!

  My name is Yeser Alfredo Morales, an electronics engineer at the University national of Engineering in Nicaragua, Since 2017 I see the potential of ROS like all that an entrepreneur Roboticist needs to make a career in Robotics.   
    
  <i class="far fa-lightbulb"></i> Ask me about: Kinematics Robotics using KDL, Pluging of Rviz - ROS, Computer Vision using OpenCV, PLC Siemens and Backend Web.
  
  <i class="fas fa-laptop-code"></i> Programming Languages:  <mark>C/C++</mark>, <mark>Python</mark>, <mark>PLC ladder</mark>, <mark>JavaScript</mark>
  
  <i class="fas fa-user-astronaut"></i> Skills: <mark>Linux</mark>, <mark>Robotics</mark>, <mark>Computer Vision</mark>, <mark>PLC Automation</mark>, <mark>Backend Web</mark>, <mark>Data Scraping</mark>
  
  ![alt text](/images/2meall.PNG "CR")


content:
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: DIVERSA - ESD
        sub_title: Electronic Systems Development Internship
        caption: (March - July 2018)
        link: https://www.diversa-esd.com/
        quote: >
          Created to develop the appropriate system to solve your problem.
        description: | # this will include new lines to allow paragraphs
          - Programming microcontrollers using C. 
          - Development of PCB boards
      - layout: left
        title: TECNODIAGNOSTICA S.A.
        sub_title: Technical support engineer
        caption: (February - September 2019)
        link: http://tecnodiagnostica.com/
        quote: >
          Integral solutions for laboratories
        description: | # this will include new lines to allow paragraphs
          - Support engineer for specialized medicine systems and equipment. 
      - layout: left
        title: SCISA
        sub_title: Automation Specialist
        caption: (September 2019 - August 2020)
        link: http://scisa.com.ni/
        quote: >
          Engineering designs and industrial automation
        description: | # this will include new lines to allow paragraphs
          - Automation project development and programming engineer.
          - Programming of control systems, usually using Siemens and Allen Bradley PLCs.
      - layout: left
        title: Bluefields Technologies S.A
        sub_title: Technical support engineer
        caption: (August 2020 - Present)
        link: 
        quote: >
           
        description: | # this will include new lines to allow paragraphs
          - Support engineer for specialized equipment on x-ray detection systems.
          - IT Support engineer.
      - layout: left
        title: LOKAFY
        sub_title: Freelance Backend developer
        caption: (January 2021 - Present)
        link: https://lokafy.com/
        quote: >
          Bring the World Closer Together
        description: | # this will include new lines to allow paragraphs
          - API Development using Sails and Django.
          - Data scraping
  - title: Academic Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Electrocardiograph
        link: https://github.com/myalfred03/EKG-PIC18F-AD620-SMD
        link_text: EKG
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/myalfred03/EKG-PIC18F-AD620-SMD
          - title:  Repo page for project
            icon: fas fa-atlas
            url: https://revistas.usac.edu.gt/index.php/cytes/article/view/297
        quote: >
          Short overview of the project
        description: | # this will include new lines to allow paragraphs
          Electrocardiograph capable of recording and transmitting data, using the Bluetooth communication protocol, to a computer. Microcontroller technology was used to implement the electrocardiograph and LABVIEW to develop the program to receive and process data in order to show the electrocardiogram in the computer screen. Data are stored in an EEPROM memory for further analysis. <mark>2nd place project automation category.</mark> in <mark>TECNO – UNI</mark> 
      - layout: left
        title: Virtual laboratory of Robotics
        link: https://github.com/myalfred03/rvizglabre/
        link_text: LVR
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/myalfred03/rvizglabre
          - title:  Repo page for project
            icon: fas fa-atlas
            url: http://ribuni.uni.edu.ni/3038/ 
        quote: >
          Short overview of the project
        description: | # this will include new lines to allow paragraphs
          The laboratory was developed with the Robotic Operating System (ROS) as its fundamental element, which has become a de facto standard for professionals dedicated to the development of robotic systems. ROS has many software tools and simulators that allow the analysis of a robotic application, whether it is real or simulated. <mark>1st place Best international project.</mark> in <mark>Second Technological Week Honduras</mark>
  - title: Education
    layout: list
    content:
      - layout: left
        title:  UNI
        sub_title: Electronics engineer
        caption: (2013 - 2017)
        quote: >
          Universidad Nacional de Ingeniería
        description: | # this will include new lines to allow paragraphs
      - layout: left
        title:  ANI
        sub_title: English Technical and intermediate competence.
        caption: (2017)
        quote: >
          Academia de idiomas
        description: | # this will include new lines to allow paragraphs
      - layout: left
        title:  EDx
        sub_title: Introduction to Cloud Infrastructure Technologies
        caption: (2019)
        quote: >
          The Linux Foundation
        description: | # this will include new lines to allow paragraphs
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I enjoy reading books with futuristic concepts and classic science fiction. I like to learn about astronomy every day, currently I have my own telescope. The concept that we are: *"Speck of dust suspended in a ray of sunlight"* teaches me humility.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
